site_name: CloudStream
copyright: "ADGSTUDIOS"
site_url: https://adgstudios.co.za
repo_url: https://github.com/adgsenpai/CloudStream-3
repo_name: adgsenpai/CloudStream-3
nav:
      - Homepage:
        - About App: index.md
theme:
      name: material
      highlightjs: true
      hljs_languages:
            - yaml
      icon:
            repo: fontawesome/brands/github
      navigation_depth: 6
      titles_only: false
      favicon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Circle-icons-cloud.svg/2048px-Circle-icons-cloud.svg.png
      logo: https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Circle-icons-cloud.svg/2048px-Circle-icons-cloud.svg.png
      features:
            - navigation.instant
      palette:
            - media: "(prefers-color-scheme: light)"
              scheme: default
              toggle:
                    icon: material/weather-sunny
                    name: Switch to dark mode
            - media: "(prefers-color-scheme: dark)"
              scheme: slate
              primary: red
              toggle:
                    icon: material/weather-night
                    name: Switch to light mode
markdown_extensions:
      - toc:
              permalink: "#"
      - smarty
      - admonition
      - footnotes
      - codehilite
      - pymdownx.arithmatex
      - pymdownx.betterem:
              smart_enable: all
      - pymdownx.caret
      - pymdownx.critic
      - pymdownx.details
      - pymdownx.emoji:
              emoji_generator: !!python/name:pymdownx.emoji.to_svg
      - pymdownx.inlinehilite
      - pymdownx.magiclink
      - pymdownx.mark
      - pymdownx.smartsymbols
      - pymdownx.superfences
      - pymdownx.tasklist:
              custom_checkbox: true
      - pymdownx.tilde
      - fontawesome_markdown
extra:
      social:
            - icon: fontawesome/brands/github
              link: "https://github.com/ADGSTUDIOS"
            - icon: fontawesome/brands/linkedin
              link: "https://www.linkedin.com/in/adgsenpai/"
      manifest: "static/site.webmanifest"